# Generated by Django 3.1.4 on 2021-04-24 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_restaurant_avg_price'),
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Request',
            new_name='Bookings',
        ),
        migrations.DeleteModel(
            name='BookConfirm',
        ),
    ]
