# Generated by Django 3.1.4 on 2021-04-22 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_customuser_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='avg_price',
            field=models.IntegerField(null=True),
        ),
    ]
