# Generated by Django 3.1.6 on 2021-05-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='is_accepted',
            field=models.CharField(default='false', max_length=10),
        ),
    ]
