# Generated by Django 3.1.6 on 2021-05-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_auto_20210526_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='booked_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
