# Generated by Django 3.1.6 on 2021-05-22 16:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20210522_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='contact',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Contact'),
            preserve_default=False,
        ),
    ]
